### ISSUE TITLE
Login Credentials Needed

### ISSUE THREAD

**Issue by Zilunl** [huanghu0/rn-expo-rebbook#1]
Hi,

I'm currently working on a project using React Native with Expo, which is similar to yours. I would like to learn from your project, but I encountered an issue while trying to log in. Could you please provide the phone number and password required for logging in?

Thank you very much for your assistance!

**Comment by huanghu0** [comment]
这个我本地要启动后端的服务 才能完成登录 自己学习的项目没有发布 只提供代电话号码和密码 给你本地没有启动服务也没有用

**Comment by Zilunl** [comment]
好的谢谢，不好意思打扰了
